import { Wallpaper } from '@/components/WallpaperCard/WallpaperCard';

export const CATEGORIES = [
  { id: 'all', label: 'All', icon: '✦' },
  { id: 'abstract', label: 'Abstract', icon: '◈' },
  { id: 'nature', label: 'Nature', icon: '❋' },
  { id: 'cyberpunk', label: 'Cyberpunk', icon: '⬡' },
  { id: 'minimalist', label: 'Minimalist', icon: '◻' },
  { id: 'anime', label: 'Anime', icon: '⬟' },
  { id: 'ai-art', label: 'AI Art', icon: '◈' },
  { id: 'space', label: 'Space', icon: '✧' },
  { id: 'architecture', label: 'Architecture', icon: '⬛' },
];

// Using Picsum Photos for realistic demo images
export const MOCK_WALLPAPERS: Wallpaper[] = [
  {
    id: '1',
    title: 'Neon Cityscape at Midnight',
    imageUrl: 'https://picsum.photos/seed/neon1/1920/1080',
    width: 16,
    height: 9,
    artist: { name: 'Alex Rivera', username: 'alexrivera', avatar: 'https://picsum.photos/seed/u1/80/80', verified: true },
    tags: ['neon', 'city', 'night'],
    downloads: 42300,
    likes: 8900,
    resolution: '4K',
    category: 'cyberpunk',
    isPremium: false,
  },
  {
    id: '2',
    title: 'Misty Forest Dawn',
    imageUrl: 'https://picsum.photos/seed/forest2/1080/1440',
    width: 3,
    height: 4,
    artist: { name: 'Priya Sharma', username: 'priyaart', avatar: 'https://picsum.photos/seed/u2/80/80', verified: true },
    tags: ['forest', 'nature', 'fog'],
    downloads: 31200,
    likes: 6700,
    resolution: '8K',
    category: 'nature',
    isPremium: true,
  },
  {
    id: '3',
    title: 'Abstract Flow Geometry',
    imageUrl: 'https://picsum.photos/seed/abstract3/1920/1200',
    width: 16,
    height: 10,
    artist: { name: 'Marco Bellini', username: 'marcoart', avatar: 'https://picsum.photos/seed/u3/80/80', verified: false },
    tags: ['abstract', 'geometry', 'colorful'],
    downloads: 18700,
    likes: 4200,
    resolution: '4K',
    category: 'abstract',
  },
  {
    id: '4',
    title: 'Minimal Desert Dunes',
    imageUrl: 'https://picsum.photos/seed/desert4/2560/1440',
    width: 16,
    height: 9,
    artist: { name: 'Yuki Tanaka', username: 'yukidesign', avatar: 'https://picsum.photos/seed/u4/80/80', verified: true },
    tags: ['desert', 'minimal', 'sand'],
    downloads: 25600,
    likes: 5100,
    resolution: '4K',
    category: 'minimalist',
  },
  {
    id: '5',
    title: 'Deep Space Nebula',
    imageUrl: 'https://picsum.photos/seed/space5/3840/2160',
    width: 16,
    height: 9,
    artist: { name: 'Cosmos Lab', username: 'cosmoslab', avatar: 'https://picsum.photos/seed/u5/80/80', verified: true },
    tags: ['space', 'stars', 'galaxy'],
    downloads: 89200,
    likes: 21000,
    resolution: '8K',
    category: 'space',
    isPremium: true,
  },
  {
    id: '6',
    title: 'Rain on Tokyo Streets',
    imageUrl: 'https://picsum.photos/seed/tokyo6/1080/1920',
    width: 9,
    height: 16,
    artist: { name: 'Kenji Mori', username: 'kenjimori', avatar: 'https://picsum.photos/seed/u6/80/80', verified: false },
    tags: ['japan', 'rain', 'street'],
    downloads: 34100,
    likes: 7800,
    resolution: '4K',
    category: 'cyberpunk',
  },
  {
    id: '7',
    title: 'Crystal Mountain Peak',
    imageUrl: 'https://picsum.photos/seed/mountain7/2560/1600',
    width: 8,
    height: 5,
    artist: { name: 'Priya Sharma', username: 'priyaart', avatar: 'https://picsum.photos/seed/u2/80/80', verified: true },
    tags: ['mountain', 'crystal', 'winter'],
    downloads: 19800,
    likes: 4500,
    resolution: '4K',
    category: 'nature',
  },
  {
    id: '8',
    title: 'Neural Network Pulse',
    imageUrl: 'https://picsum.photos/seed/neural8/1920/1080',
    width: 16,
    height: 9,
    artist: { name: 'AI Studio X', username: 'aistudiox', avatar: 'https://picsum.photos/seed/u8/80/80', verified: true },
    tags: ['ai', 'tech', 'abstract'],
    downloads: 56000,
    likes: 13200,
    resolution: '4K',
    category: 'ai-art',
    isPremium: true,
  },
  {
    id: '9',
    title: 'Golden Hour Coastline',
    imageUrl: 'https://picsum.photos/seed/coast9/2400/1600',
    width: 3,
    height: 2,
    artist: { name: 'Marco Bellini', username: 'marcoart', avatar: 'https://picsum.photos/seed/u3/80/80', verified: false },
    tags: ['coast', 'sunset', 'golden'],
    downloads: 28400,
    likes: 6100,
    resolution: '4K',
    category: 'nature',
  },
  {
    id: '10',
    title: 'Brutalist Architecture',
    imageUrl: 'https://picsum.photos/seed/arch10/1600/2400',
    width: 2,
    height: 3,
    artist: { name: 'Yuki Tanaka', username: 'yukidesign', avatar: 'https://picsum.photos/seed/u4/80/80', verified: true },
    tags: ['architecture', 'concrete', 'modern'],
    downloads: 14300,
    likes: 3100,
    resolution: '4K',
    category: 'architecture',
  },
  {
    id: '11',
    title: 'Vaporwave Dreamscape',
    imageUrl: 'https://picsum.photos/seed/vapor11/1920/1080',
    width: 16,
    height: 9,
    artist: { name: 'Alex Rivera', username: 'alexrivera', avatar: 'https://picsum.photos/seed/u1/80/80', verified: true },
    tags: ['vaporwave', 'retro', 'purple'],
    downloads: 47800,
    likes: 11200,
    resolution: '4K',
    category: 'abstract',
    isPremium: true,
  },
  {
    id: '12',
    title: 'Ancient Temple Ruins',
    imageUrl: 'https://picsum.photos/seed/temple12/2560/1440',
    width: 16,
    height: 9,
    artist: { name: 'Kenji Mori', username: 'kenjimori', avatar: 'https://picsum.photos/seed/u6/80/80', verified: false },
    tags: ['temple', 'ancient', 'ruins'],
    downloads: 22100,
    likes: 4900,
    resolution: '4K',
    category: 'architecture',
  },
];
